#! /usr/bin/env ruby

# This file prints out the CSS files that
# do not have corresponding SCSS files listed in the Gruntfile.

require 'rubygems'
require 'paint'

def sh(cmd)
  `#{cmd}`.tap do
    if $?.exitstatus > 0
      puts Paint["Shell command failed: ", :red] + " " + cmd
      exit 1
    end
  end
end

grunt_prefix = "Drupal/"
sass_output = sh "cd #{grunt_prefix} && grunt sass_watch --dry-run"

generated_css_files = sass_output[/sass.*?(sites.*)/, 1].split(" ").map { |colon_sep| grunt_prefix + colon_sep.split(":").last }

# css_files_in_git = sh("git ls-files -z -- '*.css'").split("\0")

ignored_and_untracked_css_files = sh("git ls-files -z --ignored --exclude-standard --other -- '#{grunt_prefix}**/*.css'").split("\0")

ignored_but_tracked_css_files = sh("git ls-files -z --ignored -X .gitignore -- '#{grunt_prefix}**/*.css'").split("\0")

library_file_globs = DATA.read.split("\n")

tracked_library_files = library_file_globs.map do |glob|
  sh("git ls-files -z -- '#{glob}'").split("\0")
end.flatten

untracked_library_files = library_file_globs.map do |glob|
  sh("git ls-files -z --ignored --exclude-standard --others -- '#{glob}'").split("\0")
end.flatten

all_css_files = sh("git ls-files -z -- '#{grunt_prefix}**/*.css'").split("\0")

def print_array(ary)
  if ary.empty?
    puts Paint["  (no files)", :green]
  else
    puts ary.map { |x| "  #{x}"}.join("\n")
    $exit_status = 1
  end
end

def print_header(header)
  puts Paint["\n" + header, :magenta]
end

$exit_status = 0

# ignored_but_not_generated
print_header "These files are ignored, but not generated by grunt sass_watch (maybe they should be added to the Gruntfile or listed as library code?):"
print_array(ignored_and_untracked_css_files - generated_css_files - tracked_library_files - untracked_library_files)

# generated_but_not_ignored
print_header "These files are generated by sass_watch but not ignored (maybe they should be added to .gitignore?):"
print_array(generated_css_files - ignored_and_untracked_css_files)

print_header "These files are in .gitignore but also tracked (maybe they should be removed from the repository or listed as library code?):"
print_array(ignored_but_tracked_css_files - tracked_library_files)

print_header "These files are CSS files that are not in the Gruntfile, known library list, or gitignore (maybe they should be added to a list?):"
print_array(all_css_files - generated_css_files - tracked_library_files)

exit $exit_status
